export default {
  login: "sharashena",
  id: 53409105,
  node_id: "MDQ6VXNlcjUzNDA5MTA1",
  avatar_url: "https://avatars.githubusercontent.com/u/53409105?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sharashena",
  html_url: "https://github.com/sharashena",
  followers_url: "https://api.github.com/users/sharashena/followers",
  following_url:
    "https://api.github.com/users/sharashena/following{/other_user}",
  gists_url: "https://api.github.com/users/sharashena/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sharashena/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sharashena/subscriptions",
  organizations_url: "https://api.github.com/users/sharashena/orgs",
  repos_url: "https://api.github.com/users/sharashena/repos",
  events_url: "https://api.github.com/users/sharashena/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/sharashena/received_events",
  type: "User",
  site_admin: false,
  name: "Luka Sharashenidze",
  company: null,
  blog: "https://www.facebook.com/profile.php?id=100028700561802",
  location: "Tbilisi, Georgia",
  email: null,
  hireable: null,
  bio: "Front-End Developer",
  twitter_username: null,
  public_repos: 4,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-07-28T19:42:18Z",
  updated_at: "2022-08-03T20:22:05Z",
};
